main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),

]

matkul/urls.py
from django.urls import path

from . import views

app_name = 'matkul'

urlpatterns = [
    path('daftarkan/', views.daftarkan, name='daftarkan'),
    path('data/', views.data, name='data'),
    path('data/<int:index>/', views.detail, name="detail"),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.home, name='home'),
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('experiences', views.experiences, name='experiences'),
    path('contact', views.contact, name='contact'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include('story1.urls'), name='story1'),
    path('story3/', include('story3.urls')),
    path('matkul/', include('matkul.urls')),
    path('kegiatan/', include('story6.urls'), name='kegiatan'),
    path('experiences/', include('story7.urls'), name='experiences'),
    path('book-search/', include('story8.urls'), name='book-search'),
    path('accounts/', include('story9.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls'))
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('daftarkan/', views.daftarkan, name='daftarkan'),
    path('data/', views.data, name='data'),
    
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.experiences, name='experiences')
    
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.book_search, name='book-search'),
    path('data', views.book_data, name='book-data')

]

story9/urls.py
from django.urls import path
from story9.views import sign_up

app_name = 'story9'

urlpatterns = [
    path('signup', sign_up.as_view(), name='signup'),
]

main/models.py
from django.db import models

# Create your models here.

uts/models.py
from django.db import models

# Create your models here.

matkul/forms.py
from django import forms
from .models import Matkul
from .models import SMT_CHOICES
from django.contrib.admin import models

class MatkulForm(forms.ModelForm):

    class Meta:
        model = Matkul
        fields = '__all__'
        
        
        widgets = {
            'nama':forms.TextInput(attrs={'class':'form-control'}),
            'dosen':forms.TextInput(attrs={'class':'form-control'}),
            'sks':forms.NumberInput(attrs={'class':'form-control','minlength': 1, 'maxlength': 6, 'required': True, 'type': 'number',}),
            'deskripsi':forms.Textarea(attrs={'class':'form-control'}),
            'smt':forms.Select(choices=SMT_CHOICES, attrs={'class':'form-control'}),
            'ruang':forms.TextInput(attrs={'class':'form-control'}),
        }

story6/forms.py
from django import forms
from .models import Kegiatan, Peserta
from django.contrib.admin import models

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'

        widgets = {
            'kegiatan':forms.TextInput(attrs={'class':'form-control'}) }
        
class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = '__all__'

        widgets = {
            'kegiatan': forms.Select(attrs={'class':'form-control'}),
            'nama':forms.TextInput(attrs={'class':'form-control'})
        }

main/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return render(request, 'main/home.html')

matkul/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from .models import Matkul
from .forms import MatkulForm

# Create your views here.

def daftarkan(request):
    form = MatkulForm()
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            data_input = Matkul()
            data_input.nama = data['nama']
            data_input.dosen = data['dosen']
            data_input.sks = data['sks']
            data_input.deskripsi = data['deskripsi']
            data_input.smt = data['smt']
            data_input.ruang = data['ruang']
            data_input.save()
            current_data = Matkul.objects.all()
            return render(request, 'matkul.html', {'form':form, 'status':'success', 'data':current_data})
        else:
            current_data = Matkul.objects.all()
            return render(request, 'matkul.html', {'form':form, 'status':'failed', 'data':current_data})
    else:
        current_data = Matkul.objects.all()
        return render(request, 'matkul.html', {'form':form, 'data':current_data})

def data(request):
    if request.method == 'POST':
        matkul = Matkul.objects.all()
        Matkul.objects.filter(id=request.POST['id']).delete()
        return redirect('matkul:data')
    else:
        matkul = Matkul.objects.all()
        return render(request, 'data.html', {'matkul':matkul})

def detail(request, index):
    matkul = Matkul.objects.get(pk=index)
    return render(request, 'detail.html', {'matkul':matkul})

story1/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'story1/home.html')

story3/views.py
from django.shortcuts import render

# Create your views here.

def profile(request):
    return render(request, 'story3/profile.html')\
    
def experiences(request):
    return render(request, 'story3/experiences.html')

def contact(request):
    return render(request, 'story3/contact.html')

story6/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Kegiatan, Peserta
from .forms import KegiatanForm, PesertaForm

# Create your views here.

def daftarkan(request):
    kegiatan = Kegiatan.objects.all()
    form = KegiatanForm()
    if request.method == 'POST':    
        forminput = KegiatanForm(request.POST)
        if forminput.is_valid():
            forminput.save()
            return render(request, 'keg-daftarkan.html', {'form':form, 'status': 'success', 'data' : kegiatan})
        else:
            return render(request, 'keg-daftarkan.html', {'form':form, 'status': 'failed', 'data' : kegiatan})       
    else:
        current_data = Kegiatan.objects.all()
        return render(request, 'keg-daftarkan.html', {'form':form, 'data':current_data})

def data(request):
    form = PesertaForm()
    kegiatan = Kegiatan.objects.all()
    peserta = Peserta.objects.all()
    if request.method == 'POST':
        forminput = PesertaForm(request.POST)
        if forminput.is_valid():
            forminput.save()
            return render(request,'keg-data.html', {'form':form, 'status': 'success', 'peserta' : peserta, 'kegiatan': kegiatan})
        else:
            peserta = Peserta.objects.all()
            return render(request, 'keg-data.html', {'form':form, 'status': 'failed', 'perserta' : peserta, 'kegiatan': kegiatan})
    else:
        return render(request,'keg-data.html', {'form':form, 'peserta' : peserta, 'kegiatan': kegiatan})

story7/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def experiences(request):
    return render(request, 'experiences.html')

story8/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
import requests

# Create your views here.

def book_search(request):
    return render(request, 'book-search.html')

def book_data(request):
    keyword = request.GET['buku']
    url_tujuan = 'https://www.googleapis.com/books/v1/volumes?q=' + keyword
    result = requests.get(url_tujuan)
    data = result.json()
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.

class sign_up(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/sign-up.html'

uts/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="icon" href="{% static 'img/memoji-fyz.png' %}" type="image/gif">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% endblock stylesheet %}
	<link href="https://fonts.googleapis.com/css?family=Airbnb+Cereal+App&display=swap" rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand" />
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Abril Fatface" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <link  href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.min.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
  <script src="https://kit.fontawesome.com/4ee029818e.js" crossorigin="anonymous"></script>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

	<!-- jQuery library -->
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script> -->

	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

	<!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  
 

  {% block head %}
  {% endblock head %}
</head>

<body>

  {% block navbar %}
  <!-- <h5 style="margin-top: 10px;"><a href="{% url 'matkul:daftarkan' %}">Story #5 </a>| Fayza Azzahra Robby - 1906305934</h5> -->
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#C3D2DD">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'main:home' %}">Home</a>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Stories
          </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="nav-link" href="{% url 'story1:home' %}">Story 1</a>
           <a class="nav-link" href="{% url 'story3:profile' %}">Story 3</a>
        </div>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Mata Kuliah
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'matkul:daftarkan' %}"> Daftarkan </a>
            <a class="dropdown-item" href="{% url 'matkul:data' %}">Lihat Jadwal</a>
          </div>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Kegiatan
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'story6:daftarkan' %}"> Daftarkan </a>
            <a class="dropdown-item" href="{% url 'story6:data' %}">Lihat Kegiatan</a>
          </div>
        </li>

        <a class="nav-link" href="{% url 'story7:experiences' %}">Experiences</a>
        <a class="nav-link" href="{% url 'story8:book-search' %}">Book Search</a>
        
          <a class="nav-link" style="color: salmon;" href="{% url 'story9:signup' %}">Sign Up</a>
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
          {% else %}
          <a class="nav-link" style="color: salmon;" href="{% url 'login' %}">Log In</a>
          {% endif %}

      </div>
    </div>
  </nav>
  

  
  {% endblock navbar %}
 
  
  {% block sidebar %}
  <div class="sidebar">
    <h1 class="abril-font" style="padding:0;">fayza azzahra</h1>
    <h6>Information System Student at University of Indonesia</h6>
    <a href="{% url 'main:home' %}">Home (Story 4)</a>
    <a href="{% url 'story3:profile' %}">Profile</a>
    <a href="{% url 'story3:experiences' %}">Experiences</a>
    <a href="{% url 'story3:contact' %}">Contact</a>
  
    <div class="line">
    </div>
  
    <div class="social-media">
      <a href="mailto:fayza.azzahra@gmail.com">
        <img  src="../static/story3/img/mail-icon.png" alt="mail" >
      </a>
      <a href="https://www.linkedin.com/in/fayzazzahra">
        <img  src="../static/story3/img/linkedin-icon.png" alt="linkedin" >
      </a>
      <a href="https://api.whatsapp.com/send?phone=628111111725">
        <img  src="../static/story3/img/wa-icon.png" alt="wa" width="250" >
      </a>
     <a href="https://www.instagram.com/fayzazzahra/">
      <img  src="../static/story3/img/ig-icon.png" alt="ig" width="250" >
     </a>
    </div>
  </div>
  {% endblock sidebar %}

  {% block content %}
  {% endblock content %}

  {% block script %}
  {% endblock script %}
</body>
</html>